# Generated by Django 5.0 on 2023-12-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_pdf_alter_post_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
